const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict');
const {test}=require('node:test'),lib={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../src/lib/stores-list.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:lib,require,URLSearchParams});
const row=id=>({id,slug:'store-'+id,store_name:'Store '+id,image:null});
const page=(p=1,total=51)=>({success:true,stores:Array.from({length:Math.max(0,Math.min(50,total-(p-1)*50))},(_,i)=>row((p-1)*50+i+1)),pagination:{current_page:p,last_page:Math.max(1,Math.ceil(total/50)),per_page:50,total}});
test('pagination does not duplicate page one and respects last page',()=>{assert.equal(lib.validateStoresPage(page(2),2).stores[0].id,51);assert.equal(lib.validateStoresPage(page(3),3).stores.length,0)});
test('reject truncated, false-success, duplicate and mismatched pages',()=>{for(const change of [x=>x.stores.pop(),x=>x.success=false,x=>x.stores[1]=x.stores[0],x=>x.pagination.current_page=2,x=>x.pagination.total=101,x=>x.pagination.per_page=100,x=>x.stores[0].slug='../unsafe']){let x=page();change(x);assert.throws(()=>lib.validateStoresPage(x,1));}});
test('empty catalog must have explicit coherent pagination',()=>{assert.equal(lib.validateStoresPage(page(1,0),1).stores.length,0);assert.throws(()=>lib.validateStoresPage({success:true,stores:[]},1));});
test('only positive canonical integer page numbers',()=>{for(const v of ['0','-1','01','1.5','1e3','abc','9999999999',['2']])assert.equal(lib.parseStorePage(v),null);assert.equal(lib.parseStorePage(undefined),1);assert.equal(lib.storePageHref(1),'/stores/');assert.equal(lib.storePageHref(2),'/stores/?page=2');});
test('filter bookmarks use fragments, round-trip Arabic, no external redirect',()=>{const f={category:'168',country:'السعودية',search:'عناية & https://example.org/',page:3};const url=lib.storeFilterHref(f);assert.ok(url.startsWith('/stores/#'));assert.ok(!url.includes('?'));assert.equal(JSON.stringify(lib.parseStoreFilters(new URLSearchParams(url.split('#')[1]))),JSON.stringify(f));assert.equal(lib.storeFilterHref(lib.emptyStoreFilters),'/stores/');});
test('invalid filters and huge search are bounded',()=>{const f=lib.parseStoreFilters(new URLSearchParams({category:'1 OR 1=1',page:'-1',search:'a'.repeat(300)}));assert.equal(f.category,'');assert.equal(f.page,1);assert.equal(f.search.length,200)});
test('an unnamed legacy store uses its slug without losing the page',()=>{const d=page();d.stores[0].store_name=null;const parsed=lib.validateStoresPage(d,1);assert.equal(parsed.stores.length,50);assert.equal(parsed.stores[0].store_name,'store 1');assert.equal(d.stores[0].store_name,null)});
if(process.env.STORES_FIXTURE_DIR)test('all captured live pages pass strict validation without lost stores',()=>{const pages=JSON.parse(fs.readFileSync(path.join(process.env.STORES_FIXTURE_DIR,'api-default.json'),'utf8'));const ids=pages.flatMap(p=>lib.validateStoresPage(p,p.page).stores.map(s=>s.id));assert.equal(ids.length,547);assert.equal(new Set(ids).size,547)});

